import type { ReactNode } from 'react';
import './global.css';

export const metadata = {
	description: 'Generated by create-nx-workspace',
	title: 'Welcome to clim.bz',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
